
spring:
    data:
        elasticsearch:
            properties:
                http:
                    enabled: true
                path:
                    logs: target/elasticsearch/log
                    data: target/elasticsearch/data